version: '3'
services:
  tomcat:
    build: ./tomcat
    container_name: RR170563IP01
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - mailcatcher
    links:
      - mysql:mysql
      - mailcatcher:mailcatcher
    volumes:
      - ./publish:/opt/cas/tomcat/webapps/publish

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: cascade
      MYSQL_USER: cas
      MYSQL_PASSWORD: supersecret

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 8825:80
