version: '3'
services:
  tomcat:
    build: ./tomcat
    depends_on:
      - mysql
      - mailcatcher
    container_name: RR170563IP01
    ports:
      - 9001:8080
    links:
      - mysql:mysql
      - mailcatcher:mailcatcher
    volumes:
      - ./publish:/opt/cas/tomcat/webapps/publish

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 8825:80
