version: '3'
services:
  tomcat:
    build: ./tomcat
    container_name: RR170563IP01
    ports:
      - 9001:8080
      - 8443:8443
    links:
      - mysql-cas:mysql
      - mailcatcher:mailcatcher
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/ssl:/usr/local/tomcat/ssl

  mysql-cas:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: cascade
      MYSQL_USER: cas
      MYSQL_PASSWORD: supersecret
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    build: ./web-server
    ports:
      - 9080:80
    volumes:
      - ./tomcat/webapps/publish:/usr/local/apache2/htdocs

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 9025:80

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - mysql-cas
    ports:
      - '8181:80'
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
    links:
      - mysql-cas:db
