version: '3'
services:
  tomcat:
    build: ./tomcat
    container_name: RR170563IP01
    ports:
      - 9001:8080
    links:
      - mysql-cas:mysql
      - mailcatcher:mailcatcher
    volumes:
      - ./publish:/usr/local/tomcat/webapps/publish

  mysql-cas:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: cascade
      MYSQL_USER: cas
      MYSQL_PASSWORD: supersecret

  web:
    build: ./web-server
    ports:
      - 9080:80
    volumes:
      - ./publish:/usr/local/apache2/htdocs:ro

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 9025:80
